spring.application.name=loginsystem


server.port=8099

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/login_system
spring.datasource.username=root
spring.datasource.password=kavita@13

spring.jpa.hibernate.ddl-auto=update

spring.redis.host=localhost
spring.redis.port=6379


